# Generated by Django 3.2.9 on 2021-11-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='destination',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='chair',
            name='location',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='chair',
            name='status',
            field=models.CharField(max_length=130),
        ),
    ]
