# Generated by Django 3.2.9 on 2021-11-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='chairid',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
